version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: app
    volumes:
      - ./app:/var/www/app
    environment:
      - DB_HOST=mysql8
      - DB_PORT=3306
      - DB_DATABASE=sample_db
      - DB_USERNAME=root
      - DB_PASSWORD=
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: nginx
    ports:
      - 8000:80
    working_dir: /var/www
    depends_on:
      - app
    volumes:
      - ./docker/nginx/local.conf:/etc/nginx/conf.d/default.conf
  mysql8:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: sample_db
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes: 
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf 
    ports:
      - 3306:3306
  # Docker in Docker(dind)は単体だと動かないためコンテナを分ける(参考: https://www.saltycrane.com/blog/2021/04/how-run-docker-docker-mac/)
  docker-daemon:
    container_name: "docker-daemon"
    environment:
      DOCKER_TLS_CERTDIR: ""
    image: "docker:dind"
    networks:
      "cdk-network":
        aliases:
          - "docker"
    privileged: true
  cdk:
    build:
      context: .
      dockerfile: ./docker/cdk/Dockerfile
    command: sh -c 'while [ 1 ]; do sleep 1000; done'
    container_name: "cdk"
    depends_on:
      - "docker-daemon"
    environment:
      DOCKER_HOST: "tcp://docker:2375"
    volumes:
      - .:/cdk
      - ./.aws-config:/root/.aws/config
      - ./.aws-credentials:/root/.aws/credentials
    networks:
      "cdk-network": {}
networks:
  "cdk-network":
    name: "cdk-network"