version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: app_laravel
    volumes:
      - ./app:/var/www/app
    environment:
      - DB_HOST=mysql8
      - DB_PORT=3306
      - DB_DATABASE=sample_db
      - DB_USERNAME=root
      - DB_PASSWORD=
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: nginx_laravel
    ports:
      - 8000:80
    working_dir: /var/www
    depends_on:
      - app
  mysql8:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: mysql_laravel
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: sample_db
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes: 
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf 
    ports:
      - 3306:3306
  cdk:
    build:
      context: .
      dockerfile: ./docker/cdk/Dockerfile
    container_name: cdk
    tty: true
    platform: linux/x86_64
    volumes:
        - .:/cdk
        - ./.aws-config:/root/.aws/config
        - ./.aws-credentials:/root/.aws/credentials